# Generated by Django 2.2.4 on 2019-12-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
