# Generated by Django 2.2.4 on 2019-12-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp1', '0002_auto_20191225_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='img',
            new_name='photo',
        ),
    ]
