# Generated by Django 2.2.4 on 2019-12-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp1', '0003_auto_20191225_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
